sudo: required

dist: trusty

language: node_js

node_js:
  - 8

branches:
  only:
    - master

services:
  - docker

cache:
  directories:
    - node_modules

before_install:
  - "./ci/install/before_install.sh"

install:
  - npm install

before_script:
  - docker ps
  - "./ci/build.sh"

script:
  - "echo testing harder!!! 🔥"

after_success:
  - "echo uploading some code coverage 🤓"
  - "./ci/deploy/feature.sh"

env:
  global:
    - NODE_ENV=test
    - AWS_PROFILE=serverless
    - PRODUCTION_BUCKET=serverless.strv.com
    - FEATURES_BUCKET=serverless-features.strv.com
    - FEATURES_HOSTNAME=http://${FEATURES_BUCKET}.s3-website-us-east-1.amazonaws.com
    - CLOUDFRONT_DISTRO=EDUY3HHTH9D7L
    - AWS_DEFAULT_REGION=us-east-1

    # AWS_CREDENTIALS_FILE
    - secure: btXaGk9VchTr0H1Bx8tl1IuW6ppm1iL8m+wK8lRPmUZYmQ6h2GUIkwvYMB3h3pl2YaBCTzUf+ClVgMUkpwB146h0CmUOT+5eiNVahP1H4jg6VZegQF1D9wHHWcWcAiof0bY/GMQPrGT7BK5Tt88vYCciqOLIk6Nqknn/XUSZR2Qa5JcPw7qeRctBGFM1PWrCK7QoWKc/SRzU2yK74AAsa6FhCTDYFifIAwoto9FEb3T+cqAYcJNwZP1rgpIp90TRTyPLfW8LtzgWqSnq68MoKAog0yZqSRJkYyF+ff+JXGRkzL8lzYRxL1UBIk5tnex5fxgrYTTzBnsNzp9BMCs6sciynpi/yGh0gw7cf/AGKW1w+Y+KsjQucejKLDM0RPTt5Q4uxDVXj5AvBwsCL12seZMCWttBE6nbIegAzP/IlpzeEalws2yAZ4G+uoSDFFnf4dVA2ajskx818ViCHNZnANLvfd2tiAqs2OJSmycYEDwzEYivPwV9XTuN2tQFCU5PHmNj2ZXyyM9M0tmwTeWgDL+lULiqp15YccSqEt52AcNZe5l60wAYyLvH0A2KQ6ct7idXjx2xFzcXzTpNqnxaB4C4CR9ooHGKTZDgB2TcKlilfg7UcBqcxpI/lyGDeMobWmvx+pzIRsGddcBBb9fhOli+yQ82OLFaPoCK88uIMiQ=

deploy:
- provider: script
  skip_cleanup: true
  script: "./ci/deploy/production.sh"
  on:
    branch:
      - master
    repo: jlsan92/serverless-website-meeting

notifications:
  email: false
